function []=Do_assignment_pyramids_main_parNoha(opts,assignment_opts)

%%%%%% Load variables 
load(opts.image_names);
load(opts.data_locations);
nimages=opts.nimages;
all_hist=[];

% run Hybrid on data set
if nargin<2
    assignment_opts=[];
end

display('Computing Spatial Pyramids  Assignments');
if ~isfield(assignment_opts,'type');             assignment_opts.type='Unknown';      end    %%%%%%%% The name of first histogram whose probability is to be computed
if ~isfield(assignment_opts,'level');            assignment_opts.level='Unknown';    end    %%%%%%%% The name of 2nd histogram whose probability is to be computed
if ~isfield(assignment_opts,'pyramid_type');     assignment_opts.pyramid_type='Unknown';     end    %%%%%%%%  Mother histogram ,The name of histogram whose features decide the size of histogram
if ~isfield(assignment_opts,'soft_assign');      assignment_opts.soft_assign='Unknown';    end    %%%%%%%% The name of 3rd histogram whose probability is to be computed
if ~isfield(assignment_opts,'descriptor_name');  assignment_opts.descriptor_name='Unknown';          end    %%%%%%%% The name of first index (Histogram_name)
if ~isfield(assignment_opts,'detector_name');    assignment_opts.detector_name='Unknown';        end    %%%%%%%% The name of 2nd index (histogram_name1)
if ~isfield(assignment_opts,'vocabulary_name');  assignment_opts.vocabulary_name='Unknown';         end    %%%%%%%% The name of mother index, this will decide the final size of histogram (histogram_name2)
if ~isfield(assignment_opts,'name');             assignment_opts.name='Unknown';         end    %%%%%%%% The name of 3rd indexindex, this will decide the final size of histogram (histogram_name2)


try
    assignment_opts2=getfield(load([opts.data_assignmentpath,'/',assignment_opts.name,'_settings']),'assignment_opts');
    if(isequal(assignment_opts,assignment_opts2))
        display('Recomputing Spatial Pyramids assignments for this settings');
    else
        display('Overwriting Spatial Pyramids assignment with same name, but other Assignment settings !!!!!!!!!!');
    end
end

vocabulary=getfield(load([opts.data_vocabularypath,'/',assignment_opts.vocabulary_name]),'voc');



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Parallel Version of the code %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 

%%%%%%%% compute the assignment part
jm = findResource('scheduler', 'type', 'jobmanager', 'Name', ...
                  'noha');
jb = createJob(jm, 'PathDependencies', {'/home/fahad/Matlab_code', ...
     '/home/fahad/Matlab_code:', ...
     '/home/fahad/Matlab_code/BOW:', ...
     '/home/fahad/Matlab_code/eccv2010_pyramids:', ...
     '/home/fahad/Matlab_code/Pyramid:', ...
     '/home/fahad/Matlab_code/Classification:', ...
     '/home/fahad/Matlab_code/Color:', ...
     '/home/fahad/Matlab_code/Descriptor:', ...
     '/home/fahad/Matlab_code/Detectors:', ...
     '/home/fahad/Matlab_code/Dorko_code:', ...
     '/home/fahad/Matlab_code/Dorko_code/Scripts:', ...
     '/home/fahad/Matlab_code/EF:', ...
     '/home/fahad/Matlab_code/Hyrbid_Assignment:', ...
     '/home/fahad/Matlab_code/IBPRIA_EF:', ...
     '/home/fahad/Matlab_code/Matlab_Joost:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorDifferentials:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorDifferentials/TensorArticle:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorDifferentials/TensorArticle/temp:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorDifferentials/boundary_tensor:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorDifferentials/color_sym:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorDifferentials/corel:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorDistances:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorDistances/JOURNAL:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorFeatureDetection:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorFeatureDetection/data:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorFeatureDetection/histograms:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorFeatureDetection/symmetries:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorFeatures:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorFeatures/CC_old:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorFeatures/FinalArticleTests:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorFeatures/eduard:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorFeatures/hist_data:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorFeatures/hist_data/temp:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorFeatures/temp:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorFeatures/test_data:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorFeatures/weibull:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorFeatures/weibull/temp:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/ColorInvariance:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/Harrow:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/anigauss:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/bag_of_words:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/bag_of_words/birds:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/bag_of_words/flowers:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/bag_of_words/voetbal:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/clustering:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/clustering/data:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/color_constancy:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/color_constancy/arjan:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/color_constancy/gamut:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/color_constancy/gamut/tmp:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/color_constancy/semantic_cc:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/color_constancy/semantic_cc/journal:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/jvdw_funcs:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/libraries:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/libraries/Dist:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/libraries/geom3d:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/libraries/libsvm-mat-2.86-1:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/matthijs:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/morphology:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/naming:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/naming/CN_gloria:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/naming/CN_gloria/dataset:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/naming/CN_gloria/dataset/reference:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/naming/CN_gloria/other:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/naming/ebay:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/naming/icip:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/naming/naming_journal:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/naming/naming_journal/jpeg_error:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/naming/naming_journal/optimization:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/naming/voc:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/natcho:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/plsa:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/public_software:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/public_software/ColorConstancy:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/public_software/ColorDescriptors:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/public_software/ColorDescriptors_old:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/public_software/ColorFeatures:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/public_software/ColorHarrisExample:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/public_software/ColorNaming:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/public_software/QI:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/public_software/blur:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/rein:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/rein/diffusion:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/robust_structure_tensor:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/robust_structure_tensor/optical_flow:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/robust_structure_tensor_old:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/saliency:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/scripts:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/students:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/students/nacho:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/test:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/test/plsa:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/voetbal:', ...
     '/home/fahad/Matlab_code/Matlab_Joost/voetbal/scripts:', ...
     '/home/fahad/Matlab_code/Texture_Gabor:', ...
     '/home/fahad/Matlab_code/Texture_LBP:', ...
     '/home/fahad/Matlab_code/Texture_SIFT:', ...
     '/home/fahad/Matlab_code/Texture_SIFT/SIFT_Matfiles:', ...
     '/home/fahad/Matlab_code/Texture_SIFT/SIFT_Opponent:', ...
     '/home/fahad/Matlab_code/Texture_SIFT/SIFt Code:', ...
     '/home/fahad/Matlab_code/Texture_SIFT/normal_sift:', ...
     '/home/fahad/Matlab_code/Texture_SIFT/normal_sift/data:', ...
     '/home/fahad/Matlab_code/Texture_SIFT/normal_sift/doc:', ...
     '/home/fahad/Matlab_code/Texture_SIFT/normal_sift/doc/figures:', ...
     '/home/fahad/Matlab_code/Texture_SIFT/pgm_textures:', ...
     '/home/fahad/Matlab_code/Texture_SIFT/pgm_textures/scripts:', ...
     '/home/fahad/Matlab_code/UVA_Color_Descriptor:', ...
     '/home/fahad/Matlab_code/Vocabulary:', ...
     '/home/fahad/Matlab_code/anigaussm:', ...
     '/home/fahad/Matlab_code/display_probabilities:', ...
     '/home/fahad/Matlab_code/fastkmeans:', ...
     '/home/fahad/Matlab_code/gabor_toolbox:', ...
     '/home/fahad/Matlab_code/gabor_toolbox/htmldoc:', ...
     '/home/fahad/Matlab_code/gabor_toolbox/htmldoc/simplegabortb-v1.0.0:', ...
     '/home/fahad/Matlab_code/gist:', ...
     '/home/fahad/Matlab_code/hybrid_approach:', ...
     '/home/fahad/Matlab_code/jvdw_funcs:', ...
     '/home/fahad/Matlab_code/libsvm-mat-2.84-1-fast:', ...
     '/home/fahad/Matlab_code/phog:', ...
     '/home/fahad/Matlab_code/salieny_label:', ...
     '/home/fahad/Matlab_code/spatial_pyramid_code:', ...
     '/home/fahad/Matlab_code/spatial_pyramid_code/data:', ...
     '/home/fahad/Matlab_code/spatial_pyramid_code/images:', ...
     '/home/fahad/Matlab_code/svmlin-v1.0:', ...
     '/home/fahad/Matlab_code/svmlin-v1.0/example:', ...
     '/home/fahad/Matlab_code/vlfeat:', ...
     '/home/fahad/Matlab_code/vlfeat/bin:', ...
     '/home/fahad/Matlab_code/vlfeat/bin/g64:', ...
     '/home/fahad/Matlab_code/vlfeat/bin/g64/objs:', ...
     '/home/fahad/Matlab_code/vlfeat/bin/glx:', ...
     '/home/fahad/Matlab_code/vlfeat/bin/mac:', ...
     '/home/fahad/Matlab_code/vlfeat/bin/maci:', ...
     '/home/fahad/Matlab_code/vlfeat/bin/win32:', ...
     '/home/fahad/Matlab_code/vlfeat/bin/win64:', ...
     '/home/fahad/Matlab_code/vlfeat/data:', ...
     '/home/fahad/Matlab_code/vlfeat/doc:', ...
     '/home/fahad/Matlab_code/vlfeat/doc/api:', ...
     '/home/fahad/Matlab_code/vlfeat/doc/demo:', ...
     '/home/fahad/Matlab_code/vlfeat/doc/figures:', ...
     '/home/fahad/Matlab_code/vlfeat/doc/images:', ...
     '/home/fahad/Matlab_code/vlfeat/doc/mdoc:', ...
     '/home/fahad/Matlab_code/vlfeat/doc/tutorials:', ...
     '/home/fahad/Matlab_code/vlfeat/docsrc:', ...
     '/home/fahad/Matlab_code/vlfeat/docsrc/figures:', ...
     '/home/fahad/Matlab_code/vlfeat/docsrc/images:', ...
     '/home/fahad/Matlab_code/vlfeat/src:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/aib:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/demo:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/geometry:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/imop:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/mexa64:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/kmeans:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/mexglx:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/mexmac:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/mexmaci:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/mexw32:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/misc:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/mser:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/noprefix:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/plotop:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/sift:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/special:', ...
     '/home/fahad/Matlab_code/vlfeat/toolbox/test:', ...
     '/home/fahad/Matlab_code/vlfeat/vl:', ...
     '/home/fahad/Matlab_code/vlfeat/vlfeat.xcodeproj:', ...
     '/home/fahad/Matlab_code/voc_compression:', ...
});

numTasks = 8;
%         nimages=50;
tasksPerJob = floor(nimages / numTasks);
% All_hist=Do_assignment_pyramids_lazebnik_par3_3(opts,assignment_opts,1, 50,vocabulary);

% Do_assignment_pyramids_lazebnik_par_noha(opts, assignment_opts, 1, min(nimages, 50),vocabulary);

for i = 1:tasksPerJob:nimages
      createTask(jb, @Do_assignment_pyramids_lazebnik_par_noha, 1, {opts, assignment_opts, i, min(nimages, i+tasksPerJob-1),vocabulary});
     %createTask(jb, @Do_assignment_pyramids_marcin_par, 1, {opts, assignment_opts, i, min(nimages, i+tasksPerJob-1),vocabulary});
     %createTask(jb, @Do_assignment_pyramids_lazebnik_par3_3, 1, {opts, assignment_opts, i, min(nimages, i+tasksPerJob-1),vocabulary});
end
%Do_assignment_pyramids_lazebnik_par3_3
submit(jb);
wait(jb, 'finished');
results = getAllOutputArguments(jb);

%% Write concatenator
% all_hist = cell2mat(results{:,1}');
All_hist=cell2mat(results(:,1)');

% index_list=cell2mat(results{:,2}');
% All_hist=normalize(all_hist,1);  %%% no need to normalize as in pyramids,
% histograms are normalized at each level
%%%%%%%%%%%% save the voc, the indexes and the histogram 
destroy(jb);
save ([opts.data_assignmentpath,'/',assignment_opts.name],'All_hist');
save ([opts.data_assignmentpath,'/',assignment_opts.name,'_settings'],'assignment_opts');